[package]
name = "RuSk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
anyhow = "1"
lazy_static = "1.4.0"
